/* SwoleSammy — bundled motivation (offline fallback).
   When online, the app also pulls fresh random quotes from the net. */
const QUOTES = [
  { q: 'Strong is what happens when you run out of weak.', a: 'Unknown' },
  { q: 'Sore today. Strong tomorrow.', a: 'Unknown' },
  { q: 'You don\'t have to be extreme, just consistent.', a: 'Unknown' },
  { q: 'Discipline is choosing between what you want now and what you want most.', a: 'Abraham Lincoln' },
  { q: 'The body achieves what the mind believes.', a: 'Napoleon Hill' },
  { q: 'A one-hour workout is 4% of your day. No excuses.', a: 'Unknown' },
  { q: 'Strength does not come from the body. It comes from the will.', a: 'Mahatma Gandhi' },
  { q: 'Take care of your body. It\'s the only place you have to live.', a: 'Jim Rohn' },
  { q: 'Little by little, a little becomes a lot.', a: 'Tanzanian proverb' },
  { q: 'She believed she could, so she did.', a: 'R.S. Grey' },
  { q: 'Motivation gets you started. Habit keeps you going.', a: 'Jim Ryun' },
  { q: 'You are far too smart to be the only thing standing in your way.', a: 'Jennifer Freeman' },
  { q: 'Slow progress is still progress.', a: 'Unknown' },
  { q: 'The only bad workout is the one that didn\'t happen.', a: 'Unknown' },
  { q: 'Energy and persistence conquer all things.', a: 'Benjamin Franklin' },
  { q: 'It never gets easier. You just get stronger.', a: 'Unknown' },
  { q: 'Don\'t count the days. Make the days count.', a: 'Muhammad Ali' },
  { q: 'Strive for progress, not perfection.', a: 'Unknown' },
  { q: 'Fall in love with taking care of yourself.', a: 'Unknown' },
  { q: 'What seems impossible today will one day be your warm-up.', a: 'Unknown' },
  { q: 'Your body can stand almost anything. It\'s your mind you have to convince.', a: 'Unknown' },
  { q: 'Success is the sum of small efforts repeated day in and day out.', a: 'Robert Collier' },
  { q: 'Exercise is a celebration of what your body can do, not a punishment.', a: 'Unknown' },
  { q: 'The pain you feel today will be the strength you feel tomorrow.', a: 'Unknown' },
  { q: 'Confidence comes from keeping the promises you make to yourself.', a: 'Unknown' },
  { q: 'Do something today that your future self will thank you for.', a: 'Sean Patrick Flanery' },
  { q: 'You did not wake up today to be mediocre.', a: 'Unknown' },
  { q: 'Comparison is the thief of joy.', a: 'Theodore Roosevelt' },
  { q: 'When you feel like quitting, remember why you started.', a: 'Unknown' },
  { q: 'A river cuts through rock not because of its power, but its persistence.', a: 'James N. Watkins' },
  { q: 'Sweat is just your fat crying.', a: 'Unknown' },
  { q: 'Believe in yourself and all that you are.', a: 'Christian D. Larson' },
  { q: 'Rest when you\'re tired, but don\'t quit.', a: 'Unknown' },
  { q: 'Well done is better than well said.', a: 'Benjamin Franklin' },
  { q: 'Act as if what you do makes a difference. It does.', a: 'William James' },
  { q: 'You\'re one workout away from a good mood.', a: 'Unknown' },
];
