/* ============================================================
   SWOLESAMMY — content pack (all local, no internet needed)
   type: 'affirmation' | 'muneer' | 'pickup' | 'poem_funny' | 'poem_sweet'
   phase: 'any' | 'gentle' (cycle weeks 1 & 4) | 'hype' (weeks 2 & 3)
   MUNEER: add your own lines anywhere below — more inside jokes = better.
   Everything signed Jaan(War) gets the 💌 card style automatically.
   ============================================================ */

const CONTENT = [
  /* ---------- affirmations ---------- */
  { type: 'affirmation', phase: 'any', text: 'You\'re not working out to change who you are — you\'re revealing her.' },
  { type: 'affirmation', phase: 'any', text: 'Strong looks beautiful on you.' },
  { type: 'affirmation', phase: 'any', text: 'Every rep is a love letter to your future self.' },
  { type: 'affirmation', phase: 'any', text: 'Soft heart, strong back. You can be both.' },
  { type: 'affirmation', phase: 'any', text: 'You showed up today. That\'s the prettiest thing about you.' },
  { type: 'affirmation', phase: 'any', text: 'Glow comes from consistency, not perfection.' },
  { type: 'affirmation', phase: 'any', text: 'Your body is listening to everything you tell it. Speak kindly.' },
  { type: 'affirmation', phase: 'gentle', text: 'Rest is part of the plan, princess. Take it without guilt.' },
  { type: 'affirmation', phase: 'gentle', text: 'Some weeks you lift heavy. Some weeks showing up is the lift.' },
  { type: 'affirmation', phase: 'any', text: 'She remembered who she was and the game changed.' },
  { type: 'affirmation', phase: 'any', text: 'Confidence is built one quiet morning at a time.' },
  { type: 'affirmation', phase: 'any', text: 'Your pace is perfect. This is your story, not a race.' },
  { type: 'affirmation', phase: 'any', text: 'Strong glutes, soft heart, sharp mind.' },
  { type: 'affirmation', phase: 'any', text: 'Be patient with yourself — gardens don\'t bloom overnight.' },
  { type: 'affirmation', phase: 'any', text: 'You\'re allowed to be a masterpiece and a work in progress at the same time.' },
  { type: 'affirmation', phase: 'any', text: 'Discipline is just self-love with a schedule.' },
  { type: 'affirmation', phase: 'any', text: 'The gym doesn\'t need the best version of you today. Just the version that came.' },
  { type: 'affirmation', phase: 'hype', text: 'Today\'s weights don\'t know what\'s coming. 😌' },
  { type: 'affirmation', phase: 'hype', text: 'Walk in like you own the place. You kind of do.' },
  { type: 'affirmation', phase: 'hype', text: 'Strong week. Strong girl. Add the little plate.' },
  { type: 'affirmation', phase: 'hype', text: 'You\'ve done harder things than this set. Proceed.' },
  { type: 'affirmation', phase: 'gentle', text: 'Being gentle with yourself is also a skill. You\'re training it now.' },
  { type: 'affirmation', phase: 'gentle', text: 'Slow days grow the same garden. Water it anyway, softly.' },
  { type: 'affirmation', phase: 'gentle', text: 'A short walk still tells your body: I\'ve got us.' },
  { type: 'affirmation', phase: 'any', text: 'Future you is watching this workout and smiling.' },
  { type: 'affirmation', phase: 'any', text: 'Strength isn\'t loud. It shows up, ties its hair, and begins.' },
  { type: 'affirmation', phase: 'any', text: 'You don\'t need a new plan. You need this Tuesday, done with love.' },
  { type: 'affirmation', phase: 'any', text: 'Small wins, stacked weekly, become a different life.' },
  { type: 'affirmation', phase: 'any', text: 'Your only competition is the girl from last month — and she\'s cheering for you.' },
  { type: 'affirmation', phase: 'any', text: 'Grace for the hard days. Standards for the good ones.' },
  { type: 'affirmation', phase: 'any', text: 'A water bottle, a playlist, forty minutes. That\'s all a fresh start needs.' },
  { type: 'affirmation', phase: 'any', text: 'Posture check, queen. The crown slips when you slouch. 👑' },
  { type: 'affirmation', phase: 'hype', text: 'The bar isn\'t heavy. It\'s just not used to you yet.' },
  { type: 'affirmation', phase: 'any', text: 'You are the kind of consistent that compounds.' },
  { type: 'affirmation', phase: 'any', text: 'Consistency is the most romantic thing you\'ll ever do for yourself.' },
  { type: 'affirmation', phase: 'any', text: 'You are a love letter the universe is still writing. Keep adding pages.' },
  { type: 'affirmation', phase: 'any', text: 'Every drop of sweat is glitter you can\'t see yet. ✨' },
  { type: 'affirmation', phase: 'any', text: 'You can do hard things in cute leggings.' },
  { type: 'affirmation', phase: 'any', text: 'You glow different when you keep promises to yourself.' },
  { type: 'affirmation', phase: 'any', text: 'Make your body a place you love coming home to.' },
  { type: 'affirmation', phase: 'any', text: 'Today\'s discipline is tomorrow\'s self-respect.' },
  { type: 'affirmation', phase: 'any', text: 'You didn\'t come this far to only come this far.' },
  { type: 'affirmation', phase: 'any', text: 'Lift like the woman you\'re becoming is watching. She is — and she\'s so proud.' },
  { type: 'affirmation', phase: 'any', text: 'Trust the girl who keeps showing up. She knows where she\'s going.' },
  { type: 'affirmation', phase: 'any', text: 'Your comeback is always bigger than your setback.' },
  { type: 'affirmation', phase: 'any', text: 'Hard things build soft confidence. Keep going.' },
  { type: 'affirmation', phase: 'any', text: 'Tiny effort today, plot twist tomorrow.' },
  { type: 'affirmation', phase: 'hype', text: 'Queens don\'t skip leg day; they ascend thrones. 👑' },
  { type: 'affirmation', phase: 'hype', text: 'You\'re allowed to take up space. Now go get under that bar.' },
  { type: 'affirmation', phase: 'hype', text: 'Be the kind of strong that makes your future self cry happy tears.' },
  { type: 'affirmation', phase: 'gentle', text: 'Bloom in your own time. Roses don\'t rush, and neither do you.' },
  { type: 'affirmation', phase: 'gentle', text: 'You\'re not behind. You\'re exactly on your own beautiful schedule.' },
  { type: 'affirmation', phase: 'gentle', text: 'Rest today, rise tomorrow. The plan still loves you.' },
  { type: 'affirmation', phase: 'gentle', text: 'Be patient. The seeds you\'re planting are loud underground.' },
  { type: 'affirmation', phase: 'any', text: 'Some days you chase the pump, some days you chase peace. Both count.' },
  { type: 'affirmation', phase: 'any', text: 'Strength looks like you — hair tied back, deciding to begin.' },
  { type: 'affirmation', phase: 'any', text: 'You vs you. And honestly? You\'re winning.' },
  { type: 'affirmation', phase: 'any', text: 'A little progress each day adds up to a whole new you.' },

  /* ---------- messages from Muneer 💌 (edit me!) ---------- */
  { type: 'muneer', phase: 'any', text: 'Are you a hip thrust? Because you make my heart do reps. 💌' },
  { type: 'muneer', phase: 'any', text: 'Gym crush alert 🚨 oh wait, that\'s my girlfriend.' },
  { type: 'muneer', phase: 'any', text: 'I built you a whole app because "you\'re so strong babe" didn\'t feel like enough.' },
  { type: 'muneer', phase: 'any', text: 'Warning: excessive glute gains may result in your boyfriend staring. Proceed anyway.' },
  { type: 'muneer', phase: 'any', text: 'You + dumbbells = my favourite love triangle.' },
  { type: 'muneer', phase: 'gentle', text: 'The app says rest day. I say nap on my shoulder day.' },
  { type: 'muneer', phase: 'any', text: 'Legally obligated to tell you that you\'re the strongest cutest person in this gym.' },
  { type: 'muneer', phase: 'any', text: 'Every rep you log, I\'m somewhere being proud of you. 💌' },
  { type: 'muneer', phase: 'any', text: 'You don\'t need to change a single thing. I just want you to feel as strong as I already know you are.' },
  { type: 'muneer', phase: 'any', text: 'I fell for you way before the gains. The gains are just a bonus.' },
  { type: 'muneer', phase: 'any', text: 'Strongest girl I know — and I don\'t mean the weights.' },
  { type: 'muneer', phase: 'gentle', text: 'Tired today? Borrow some of my belief in you. I have extra.' },
  { type: 'muneer', phase: 'any', text: 'One day I\'ll tell our story and this app will be a chapter.' },
  { type: 'muneer', phase: 'any', text: 'You showing up for yourself is my favourite thing to watch.' },
  { type: 'muneer', phase: 'gentle', text: 'Rough week? Heat pad\'s on me, hugs are free, you\'re still my champion. 💌' },
  { type: 'muneer', phase: 'gentle', text: 'Rest, sayang. The weights will wait. I\'m not going anywhere either.' },
  { type: 'muneer', phase: 'any', text: 'You make pre-workout obsolete — I\'m already hyped just thinking about you. 💌' },
  { type: 'muneer', phase: 'any', text: 'Plot twist: the strongest thing in this app is how hard I fell for you.' },
  { type: 'muneer', phase: 'any', text: 'If loving you was a lift, I\'d have hit a personal best on day one.' },
  { type: 'muneer', phase: 'any', text: 'I don\'t need a spotter. I\'ve got you, and that\'s enough to hold anything up. 💌' },
  { type: 'muneer', phase: 'any', text: 'You, your little water bottle, and your playlist — cutest sight in all of Singapore.' },
  { type: 'muneer', phase: 'gentle', text: 'Rest day rules: you, me, snacks, and zero guilt. Non-negotiable. 💌' },
  { type: 'muneer', phase: 'any', text: 'Other girls have a type. You\'re the entire genre.' },
  { type: 'muneer', phase: 'any', text: 'You log a set, I fall a little harder. At this rate I\'m doomed — happily.' },
  { type: 'muneer', phase: 'any', text: 'Marry me— I mean, finish your set. We\'ll talk after. 😅💌' },
  { type: 'muneer', phase: 'any', text: 'You being strong is a bonus. I\'d adore you no matter what\'s on the bar.' },
  { type: 'muneer', phase: 'gentle', text: 'I believe in you on the days you forget to. That\'s my whole job, and I love it. 💌' },
  { type: 'muneer', phase: 'gentle', text: 'Cramps today? I\'m on heat-pad duty and forehead-kiss duty. Reporting for love. 💌' },
  { type: 'muneer', phase: 'hype', text: 'Go be unreasonably strong today. I\'ll be over here, completely obsessed with you.' },

  /* ---------- pickup lines — signed Jaan(War) 🐯💌 ---------- */
  { type: 'pickup', phase: 'any', text: 'Are you a personal best? Because I\'d brag about you to everyone.' },
  { type: 'pickup', phase: 'any', text: 'Do you believe in love at first set, or should I walk past the squat rack again?' },
  { type: 'pickup', phase: 'any', text: 'Are you a rest timer? Because I can\'t stop counting down to you.' },
  { type: 'pickup', phase: 'any', text: 'Excuse me, is this machine taken? No? Great — anyway, you\'re gorgeous.' },
  { type: 'pickup', phase: 'any', text: 'They said pick a workout partner for life. I picked the cutest one.' },
  { type: 'pickup', phase: 'any', text: 'Are you a protein shake? Because you\'re the best part of my day and kind of essential.' },
  { type: 'pickup', phase: 'hype', text: 'Girl, are you progressive overload? Because you get more impressive every single week.' },
  { type: 'pickup', phase: 'any', text: 'I\'d say you stole my heart, but honestly I handed it over voluntarily.' },
  { type: 'pickup', phase: 'gentle', text: 'Are you a deload week? Because being around you feels like one big exhale.' },
  { type: 'pickup', phase: 'any', text: 'Is your name Cardio? Because you leave me breathless and slightly sweaty.' },
  { type: 'pickup', phase: 'any', text: 'Are you DOMS? Because two days later I\'m still feeling you.' },
  { type: 'pickup', phase: 'any', text: 'Do you lift? Because you just picked up my entire mood.' },
  { type: 'pickup', phase: 'hype', text: 'Are you a PR? Because my heart rate spikes every time you walk in.' },
  { type: 'pickup', phase: 'any', text: 'Are you a kettlebell? Because I\'d happily swing my whole life around you.' },
  { type: 'pickup', phase: 'any', text: 'You\'re the only superset I want — you and me, no rest between.' },
  { type: 'pickup', phase: 'any', text: 'Call you my warm-up? Never. You\'re the main event, always.' },
  { type: 'pickup', phase: 'any', text: 'Are you a personal trainer? Because I\'d let you correct my form forever.' },
  { type: 'pickup', phase: 'any', text: 'If you were a macro, you\'d be all of them — because you\'re everything.' },

  /* ---------- funny poems (4-liners) ---------- */
  { type: 'poem_funny', phase: 'any', text: 'Roses are red,\ndumbbells are grey,\nyou hip-thrusted my heart\nclean out of my chest today.' },
  { type: 'poem_funny', phase: 'any', text: 'I wrote you a poem\nbetween set two and three,\nit\'s mostly just "wow"\nand "marry— I mean, text me."' },
  { type: 'poem_funny', phase: 'any', text: 'The treadmill is boring,\nthe StairMaster\'s a crime,\nbut watching you crush it?\nEntertainment, prime.' },
  { type: 'poem_funny', phase: 'hype', text: 'Leg day is heavy,\nmy love is heavier,\ntogether they make you\nofficially deadlier.' },
  { type: 'poem_funny', phase: 'any', text: 'I counted your reps\nand lost count at three,\nnot because of the math —\nyou\'re distracting to me.' },
  { type: 'poem_funny', phase: 'gentle', text: 'The couch made a case,\nthe blanket agreed,\na rest day with you\nis all that I need.' },
  { type: 'poem_funny', phase: 'any', text: 'Your form is flawless,\nmy jaw\'s on the floor,\nI came for a workout\nbut I\'m staring once more.' },
  { type: 'poem_funny', phase: 'any', text: 'You squat to the ground,\nyou rise like the sun,\nmeanwhile I\'m winded\nfrom watching you, hon.' },
  { type: 'poem_funny', phase: 'any', text: 'I tried to act cool\nwhile you hit your PR,\nbut I clapped like a seal —\nthat\'s just who you are.' },
  { type: 'poem_funny', phase: 'any', text: 'My cardio plan\nis honestly just\nkeeping up with a girl\nwho lifts heavy. I must.' },
  { type: 'poem_funny', phase: 'gentle', text: 'Rest day, you say?\nThe couch and I cheer.\nBring blankets and you —\nwe\'ll happily disappear.' },

  /* ---------- sweet poems & lovely lines ---------- */
  { type: 'poem_sweet', phase: 'any', text: 'You are not a before picture. You were never a before picture.\nYou\'re the whole story, mid-chapter, getting good.' },
  { type: 'poem_sweet', phase: 'any', signed: true, text: 'Some flowers bloom loudly.\nSome bloom quietly, every single day,\nand don\'t even notice.\nYou\'re the second kind.' },
  { type: 'poem_sweet', phase: 'any', text: 'Strong isn\'t the opposite of soft.\nYou\'re the proof.' },
  { type: 'poem_sweet', phase: 'any', text: 'She moved gently through the world\nand the world had no idea\nhow much iron she carried\nin her hands and in her heart.' },
  { type: 'poem_sweet', phase: 'any', text: 'One day you\'ll catch your reflection\nmid-laugh, mid-lift, mid-life —\nand realise you became her\nwithout noticing.' },
  { type: 'poem_sweet', phase: 'any', signed: true, text: 'I don\'t love you because you\'re strong.\nYou\'re strong, and I love you,\nand both keep being true.' },
  { type: 'poem_sweet', phase: 'gentle', text: 'Even the moon takes nights off\nand no one calls her lazy.\nRest like the moon.\nReturn like the tide.' },
  { type: 'poem_sweet', phase: 'any', text: 'Quietly, weekly, kindly —\nthat\'s how she built herself.\nNo announcement.\nJust arrival.' },
  { type: 'poem_sweet', phase: 'any', text: 'You are proof that gentle hands\nand a will of iron\ncan live in the same girl —\nand make her unstoppable.' },
  { type: 'poem_sweet', phase: 'any', signed: true, text: 'I hope one day you see yourself\nthe way I always have:\nstrong, softening nothing,\nentirely, unmistakably you.' },
  { type: 'poem_sweet', phase: 'any', text: 'You are not a project to finish.\nYou are a garden to tend.\nAnd oh — the way you\'re blooming.' },
  { type: 'poem_sweet', phase: 'any', signed: true, text: 'Some love stories are loud.\nOurs is you, showing up quietly,\nand me, quietly undone by it.' },
  { type: 'poem_sweet', phase: 'any', text: 'The bravest thing\nisn\'t lifting heavy.\nIt\'s believing you\'re worth\nthe effort. You are.' },
  { type: 'poem_sweet', phase: 'any', text: 'When it\'s hard, remember:\nyou\'re the kind of woman\nwho keeps her promises —\neven the ones whispered to herself.' },
  { type: 'poem_sweet', phase: 'any', signed: true, text: 'Softly, fiercely, daily —\nthat is how mountains move,\nand how you became\nthe strongest gentle thing I know.' },
  { type: 'poem_sweet', phase: 'gentle', text: 'Rest, love. The iron isn\'t going anywhere,\nand neither is the woman you\'re becoming.\nShe\'s patient. She\'s sure. She\'s you.' },
  { type: 'poem_sweet', phase: 'gentle', signed: true, text: 'On the heavy days, lean on me.\nI was built a little sturdy\non purpose — for exactly\nthe weeks you feel light.' },
];

/* Rotation weights — more of his corny, romantic lines surface now:
   ~32% affirmations · ~33% Muneer + pickup · ~20% lovely lines · ~15% funny poems */
const CONTENT_WEIGHTS = { affirmation: 32, muneer: 20, pickup: 13, poem_sweet: 20, poem_funny: 15 };
